import { Router } from 'express';
import hospitalRoutes from './hospitals';
import treatmentRoutes from './treatments';
import doctorRoutes from './doctors';
import billRoutes from './bills';
import costRoutes from './costs';
import statsRoutes from './stats';
import symptomRoutes from './symptoms';
import scoreRoutes from './scores';
import ocrRoutes from './ocr';
import gamificationRoutes from './gamification';
import intelligenceRoutes from './intelligence';
import reviewRoutes from './reviews';
import seoRoutes from './seo';
import adminAuthRoutes from './adminAuth';
import adminOpsRoutes from './adminOps';
import complianceRoutes from './compliance';
import partnerRoutes from './partners';
import insuranceRoutes from './insurance';
import b2bRoutes from './b2bApi';
import userAuthRoutes from './userAuth';

export const router = Router();

router.use('/hospitals', hospitalRoutes);
router.use('/treatments', treatmentRoutes);
router.use('/doctors', doctorRoutes);
router.use('/bills', billRoutes);
router.use('/costs', costRoutes);
router.use('/stats', statsRoutes);
router.use('/symptoms', symptomRoutes);
router.use('/scores', scoreRoutes);
router.use('/community', gamificationRoutes);
router.use('/intelligence', intelligenceRoutes);
router.use('/reviews', reviewRoutes);
router.use('/seo', seoRoutes);
router.use('/compliance', complianceRoutes);
router.use('/admin/auth', adminAuthRoutes);
router.use('/admin/ocr', ocrRoutes);
router.use('/admin/ops', adminOpsRoutes);
router.use('/partners', partnerRoutes);
router.use('/insurance', insuranceRoutes);
router.use('/b2b', b2bRoutes);
router.use('/auth', userAuthRoutes);
